global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'flask-app'
    scrape_interval: 5s
    static_configs:
      - targets: ['app:5001']
        labels:
          group: 'production'

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']